### PR TITLE
A prototype

### PR DESCRIPTION
**Pull request by thanasibakis**
I've implemented a prototype of the pipeline from data pre-processing, to modeling of lineage proportions, to post-processing. I also have a simulation study implemented.

Some short-term wishlist items (these could likely be separate PRs):
- The simulation study results could look better as we generalize out of the 2 divisions, 2 lineages setting
- poetry
- Thinking harder about priors

### CODE REVIEW

**Review by swo — APPROVED** [review]
I could pick at different pieces, but I think it's more worth it to just get some code merged in!

**Comment by swo** [comment]
@thanasibakis CFA practice is that the author (ie you, not the reviewers) do the squash & merge

**Comment by thanasibakis** [comment]
Not to sneak commits in post-review, but I don't know how my simulation study sample size configuration was lost at some point. Results are looking much nicer now that I have that back :)

(Changes are very minor)

**Comment by afmagee42** [comment]
This is definitely _not_ something to pile into this PR (it's entirely separable and can be handled after merging), but some basic documentation would be good.

For example, after some poking around I can see that one should run `python load_metadata.py` before I try to run the simulations, and it would be good for the README to mention this.

**Comment by thanasibakis** [comment]
Totally. I think that would be good for me to do when I package things up with poetry (which is up next for this codebase)

**Review by afmagee42 — APPROVED** [review]

**Pull request merged**
